### ISSUE TITLE
Application crash, when localStorage disabled from browser settings

### ISSUE THREAD

**Issue by VoloshchenkoAl** [zeusdeux/observe-element-in-viewport#1]
Hi there.

I have found an error that relates to this package.

`Uncaught SecurityError: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.`

About this error from the chromium project:
https://www.chromium.org/for-testers/bug-reporting-guidelines/uncaught-securityerror-failed-to-read-the-localstorage-property-from-window-access-is-denied-for-this-document

**Comment by zeusdeux** [comment]
Ah nice catch! The fix is easy and has to do with the lines that use localStorage for the debug property. Feel free to open a PR removing the debug code since it’s fairly useless and is a dev artifact. That should fix it. 

If not, I’ll take a look over the weekend. ^_^

**Comment by zeusdeux** [comment]
Fix landed in version 0.0.12. Thanks for the report and PR @VoloshchenkoAl!
